version: '3'
services:
  nginx:
    image: nginx:1.0
    container_name: nginx
    build: requirements/nginx
    volumes:
      - ssl:/etc/nginx/ssl
      - wp_files:/var/www/html
    ports:
      - "443:443"
    networks:
      - network
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    image: wordpress:1.0
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wp_files:/var/www/html
    networks:
      - network
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: unless-stopped
    
  mariadb:
    image: mariadb:1.0
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - network
    env_file:
      - .env
    restart: unless-stopped
  
  # bonus
  ftp:
    image: ftp:1.0
    container_name: ftp
    build: requirements/bonus/ftp
    volumes:
      - wp_files:/var/www/html
    ports:
      - "20:20"
      - "21:21"
      - "40000-40002:40000-40002"
    networks:
      - network
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: unless-stopped
  
  static:
    image: static:1.0
    container_name: static
    build: requirements/bonus/static
    networks:
      - network
    restart: unless-stopped
  
  adminer:
    image: adminer:1.0
    container_name: adminer
    build: requirements/bonus/adminer
    networks:
      - network
    depends_on:
      - mariadb
    restart: unless-stopped
  
  redis:
    image: redis:1.0
    container_name: redis
    build: requirements/bonus/redis
    networks:
      - network
    depends_on:
      - wordpress
    restart: unless-stopped
  
  cadvisor:
    image: cadvisor:1.0
    container_name: cadvisor
    build: requirements/bonus/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - network
    restart: unless-stopped

volumes:
  ssl:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ricky/data/ssl

  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ricky/data/html
  
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ricky/data/db
    
  prometheus:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ricky/data/prometheus

networks:
  network:
    driver: bridge
