version: '3'
services:
  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ssl_volume:/etc/nginx/ssl

volumes:
  ssl_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ricky0625/data/ssl
