version: '3'
services:
  nginx:
    build: requirements/nginx
    volumes:
      - ssl_volume:/etc/nginx/ssl
      - html_volume:/var/www/html
    ports:
      - "443:443"
    networks:
      - network
    depends_on:
      - wordpress

  wordpress:
    build: requirements/wordpress
    volumes:
      - html_volume:/var/www/html
    networks:
      - network
    env_file:
      - .env
    depends_on:
      - mariadb
    
  mariadb:
    build: requirements/mariadb
    networks:
      - network
    env_file:
      - .env

volumes:
  ssl_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ricky0625/data/ssl

  html_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ricky0625/data/html

networks:
  network:
    driver: bridge
